#### WORKFLOW #####

# Name of the Workflow

name: CICD

# when does the workflow run

on: push

       #### JOBS #####

          jobs:

code:

runs-on: ubuntu-latest

steps:

- name: Code checkout
uses : actions/checkout@v7
run: echo "Code checkout done"

build:
needs : code
runs-on: ubuntu-latest

steps:

- name: Code Build with Docker
uses : echo"docker"
run: echo "Code build done"

test:

runs-on: ubuntu-latest

steps:

- name: Code test

run: echo "Code test done"

deploy:

runs-on: ubuntu-latest

steps:

- name: Code Deploy

run: echo "Code deploy done"
